version: "3"

volumes:
  db_1:

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!P@ssw0rd
    volumes:
      - db_1:/var/lib/postgresql/data
